name: Release Binaries

on:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Set env
        id: app_info
        run: |
          echo ::set-output name=APP_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=APP_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=APP_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=APP_COMMIT::${GITHUB_SHA}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
