name: Release Binaries

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set APP_COMMIT env
        run: echo APP_COMMIT=${GITHUB_SHA} >> ${GITHUB_ENV}

      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: "amd64"
          ldflags: "-X 'haoyu.love/ImageServer/version.Version=${{ env.APP_VERSION }}' -X 'haoyu.love/ImageServer/version.Build=${{ env.APP_COMMIT }}'"
